### ISSUE TITLE
use standard configuration directory

### ISSUE THREAD

**Issue by sbourdeauducq** [OxfordIonTrapGroup/wand#30]
Python package directories are not meant to store writable user configuration data.
Quick patch: https://git.m-labs.hk/M-Labs/nix-scripts/src/branch/master/artiq-full/wand-fix-config-dir.patch

**Comment by hartytp** [comment]
thanks! I acknowledge the issue and overall the fix looks good, but (a) I need to coordinate with current users to find a minimally disruptive time to role this out so it doesn't break things unexpectedly (b) I need to have a think about whether I actually want to make `artiq` a dependency of this package.

PS out of curiosity, are you using this for a hobby project or is another uni group using wand?

**Comment by sbourdeauducq** [comment]
Joe wants to use it on Nix, which enforces read-only package files. Sadly, I don't have enough hobby budget for a lot of wavemeters and SFPIs.

**Comment by hartytp** [comment]
aah, ok. Always nice to gather users...

I'm swamped for the next couple of days, but I'll find time to merge a fix to this this week. If it's causing you issues please do chase me.

**Comment by sbourdeauducq** [comment]
Not a high priority, I'm applying the patch in the packaging, so it already works.

**Comment by sbourdeauducq** [comment]
And yes, ARTIQ shouldn't be a dependency just for this - I just imported it because wand already depended on it.

**Comment by hartytp** [comment]
aah, oops, yes. That's probably a hang over from the pre-`sipyco` days and should be changed.

**Comment by hartytp** [comment]
TBH I'm not sure how this didn't come up before...AFAICT our current conda package for wand server cannot possibly work since it assumes a local checkout. I'll fix it...

**Comment by dnadlinger** [comment]
> TBH I'm not sure how this didn't come up before...AFAICT our current conda package for wand server cannot possibly work since it assumes a local checkout

Yep, we are indeed running a local checkout e.g. in lab 1.

**Comment by hartytp** [comment]
okay, I've fixed that and a few other issues on our fork. I'll send some PRs over in a few days once I've had a go at (a) quamash -> qasync (which AFAICT is the most live project of its ilk) and (b) using the WLM as an OSA.

**Comment by sbourdeauducq** [comment]
> using the WLM as an OSA

What WLM is that?

**Comment by hartytp** [comment]
WS*

**Comment by sbourdeauducq** [comment]
The Highfinesse Fizeau/Snyder units? They can do OSA now?

**Comment by hartytp** [comment]
Just exporting the interferometer pattern gives a lot of information about how happy the laser is

**Comment by sbourdeauducq** [comment]
But do you get the actual spectrum or just something that approximates it? Aren't there multiple reflections in these interferometers, so they are more like etalons and don't just give the autocorrelation of the laser?

**Comment by cjbe** [comment]
that's correct, but you can still end up telling by eye when the laser is single mode or not. This is used when manually tuning the laser up, and there is a clear plateau when increasing the current where the etalon signal does not change, hence the laser is single mode.

**Comment by dnadlinger** [comment]
Yep; a "proper" OSA is more sensitive (especially with a logarithmic detector), but for choosing ECDL operating points, the WS* interferometer signals are enough information – particularly if you have and idea how the "known-good" single-mode pattern should look like. Back when I was in Jonathan Home's group, we didn't use any OSAs either.

**Comment by hartytp** [comment]
I do think that it would be easier to automate the multimodw detection/correction with a proper osa if that was something one wanted to do however

**Comment by dnadlinger** [comment]
Fixed in #33.
