### ISSUE TITLE
min exposure

### ISSUE THREAD

**Issue by hartytp** [OxfordIonTrapGroup/wand#41]
currently wand doesn't allow 0ms exposures, while the HF software does. In the source I see the following somewhat cryptic statement. @cjbe @dnadlinger any ideas what the issue was here? Otherwise I'll try removing it and see what breaks

https://github.com/OxfordIonTrapGroup/wand/blob/1fb4ac42d341e80e5afdb84c987683189e4597f3/wand/drivers/high_finesse.py#L105-L107

**Comment by hartytp** [comment]
this seems to work absolutely fine on our WS7. Maybe this is an issue with one of the really old models.

@cjbe @dnadlinger any objection to me allowing 0ms min exposures after a bit more testing here?

**Comment by dnadlinger** [comment]
I'm not aware of any specifics regarding this.

**Comment by cjbe** [comment]
Me neither

**Comment by hartytp** [comment]
Some observations:
- CCD 1 seems to work as expected
- Setting the CCD 2 exposure to 1ms deterministically gives errors on our WS7 (0,2, etc are all fine AFAICT)
- looking on the HF GUI if one starts at 0ms and clicks up, the trace gets taller, but the number changes ~1s later to 2ms without user input and without the trace height changing. Similarly going down from 2ms to 1ms the trace gets lower but then the exposure changes to 0ms without intervention/a further change in trace height.

So it seems that there is no 1ms exposure...another undocumented feature courtesy of high-finesse. I'll push a suitably scummy hack to this shortly

**Comment by hartytp** [comment]
I'll spin up a PR to do this. However, given the state of the HF software it's quite possible that the hack will not work on other models. Only one way to find out though...
