### ISSUE TITLE
License text

### ISSUE THREAD

**Issue by danielwbn** [OxfordIonTrapGroup/wand#56]
Greetings! Would it be possible to add another license to your project, preferably MIT or BSD license?

Background:
I recently started working for TOPTICA Photonics and we would like to use your code. However, your zero-clause Guthrie license does not explicitly state that we may use and modify it, etc.

**Comment by hartytp** [comment]
yeah, we can accommodate that. I'll make it Apache unless anyone complains.

**Comment by hartytp** [comment]
If you submit a PR that changes the license to Apache then I will happily merge it

**Comment by dnadlinger** [comment]
Fixed in https://github.com/OxfordIonTrapGroup/wand/pull/58.
